apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app
type: Opaque
stringData:
  DATABASE_URL: "postgres://user:password@localhost:5432/devopsdb"
  REDIS_URL: "redis://localhost:6379"
  JWT_SECRET: "devopslab-jwt-secret-dev-only"
